use DbPratice

GO

CREATE TABLE LoaiXe
(
	LX_ID VARCHAR(20) PRIMARY KEY,
	LX_TEN NVARCHAR(100) NULL,
	LX_MO_TA NVARCHAR(1000) NULL,
	RECORD_STATUS varchar(1) NULL,
	MAKER_ID varchar(12) NULL,
	CREATE_DT datetime NULL, 
	AUTH_STATUS varchar(50) NULL,
	CHECKER_ID varchar(12) NULL,
	APPROVE_DT datetime NULL
)

------------------------------------------------------------
GO
/****** OBJECT:  STOREDPROCEDURE [DBO].[LOAI_XE_SEARCH]    SCRIPT DATE: 30/04/2020 5:54:20 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [DBO].[LoaiXe_Search] @LX_TEN NVARCHAR(100), @LX_MO_TA NVARCHAR(1000), @RECORD_STATUS varchar(1)
AS
BEGIN
	SELECT * FROM LoaiXe
	WHERE (@LX_TEN IS NULL OR @LX_TEN= '' OR LX_TEN LIKE '%' + @LX_TEN + '%')
	AND	(@LX_MO_TA IS NULL OR @LX_MO_TA = '' OR LX_MO_TA LIKE '%' + @LX_MO_TA + '%')
	AND (@RECORD_STATUS is null or @RECORD_STATUS = '' or RECORD_STATUS like '%' + @RECORD_STATUS + '%')
END
----------------------------------------------------------------
GO
/****** OBJECT:  STOREDPROCEDURE [DBO].[LOAI_XE_BYID]    SCRIPT DATE: 30/04/2020 5:55:04 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [DBO].[LoaiXe_ById] @LX_ID VARCHAR(20)
AS
BEGIN
	SELECT * FROM LoaiXe
	WHERE @LX_ID=LX_ID
END
--------------------------------------------------------------
GO
/****** OBJECT:  STOREDPROCEDURE [DBO].[LOAI_XE_INSERT]    SCRIPT DATE: 30/04/2020 5:55:26 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [DBO].[LoaiXe_Insert] @LX_TEN NVARCHAR(100)=NULL, @LX_MO_TA NVARCHAR(1000)=NULL,
	@RECORD_STATUS varchar(1)=NULL,
	@MAKER_ID varchar(12)=NULL,
	@CREATE_DT datetime=NULL,
	@AUTH_STATUS varchar(50)=NULL,
	@CHECKER_ID varchar(12)=NULL,
	@APPROVE_DT datetime=NULL
AS
BEGIN TRY
BEGIN TRANSACTION

declare @LX_ID varchar(20) = NULL
exec SYS_ID_Gen 'LoaiXe', @LX_ID out

	
INSERT INTO [dbo].[LoaiXe](LX_ID,LX_TEN,LX_MO_TA,RECORD_STATUS,MAKER_ID,CREATE_DT,AUTH_STATUS
           ,CHECKER_ID,APPROVE_DT)
values (@LX_ID,@LX_TEN,@LX_MO_TA,@RECORD_STATUS,@MAKER_ID,@CREATE_DT,@AUTH_STATUS,@CHECKER_ID,@APPROVE_DT)

COMMIT TRANSACTION
SELECT '0' AS RESULT, 'them thanh cong '+@LX_ID AS ID
END TRY
BEGIN CATCH

ROLLBACK TRANSACTION

END CATCH
-------------------------------------------------------------------
GO
/****** OBJECT:  STOREDPROCEDURE [DBO].[LOAI_XE_DELETE]    SCRIPT DATE: 30/04/2020 5:55:26 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [DBO].[LoaiXe_Delete] @LX_ID VARCHAR(20)
AS
BEGIN
	DELETE FROM LoaiXe WHERE LX_ID = @LX_ID
END
-------------------------------------------------------------------
GO
/****** OBJECT:  STOREDPROCEDURE [DBO].[LOAI_XE_UPDATE]    SCRIPT DATE: 30/04/2020 5:55:26 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [DBO].[LoaiXe_Update] @LX_ID VARCHAR(20) = NULL,
	@LX_TEN NVARCHAR(100)=NULL,
	@LX_MO_TA NVARCHAR(1000)=NULL,
	@RECORD_STATUS varchar(1)=NULL,
	@MAKER_ID varchar(12)=NULL,
	@CREATE_DT datetime=NULL,
	@AUTH_STATUS varchar(50)=NULL,
	@CHECKER_ID varchar(12)=NULL,
	@APPROVE_DT datetime=NULL
AS
BEGIN TRY
IF(NOT EXISTS(SELECT * FROM LoaiXe WHERE LX_ID <> @LX_ID ))
BEGIN
	SELECT '-1' RESULT, N'MÃ LOẠI XE KHÔNG HỢP LỆ' ERROR_DESC
	RETURN
END

BEGIN TRANSACTION
UPDATE [DBO].[LoaiXe]
   SET [LX_TEN] = @LX_TEN
      ,[LX_MO_TA] = @LX_MO_TA,
		[RECORD_STATUS]=@RECORD_STATUS,
		[MAKER_ID]=@MAKER_ID,
		[CREATE_DT]=@CREATE_DT,
		[AUTH_STATUS]=@AUTH_STATUS,
		[CHECKER_ID]=@CHECKER_ID,
		[APPROVE_DT]=@APPROVE_DT      
	WHERE [LX_ID] = @LX_ID

COMMIT TRANSACTION
SELECT '0' AS RESULT, @LX_ID AS ID
END TRY
BEGIN CATCH

ROLLBACK TRANSACTION

END CATCH