DROP PROC LOAI_XE_GET_ALL
GO

DROP PROC LOAI_XE_SEARCH_2
GO

CREATE PROC [dbo].[LoaiXe_GetAll] AS
BEGIN
	SELECT * FROM [dbo].[LoaiXe] WHERE RECORD_STATUS IS NULL OR RECORD_STATUS <> '0'
END
GO

CREATE PROC dbo.LoaiXe_SearchWithOption (
@TO_SEARCH NVARCHAR(255), @SEARCH_TYPE VARCHAR(255)
) AS
BEGIN
	IF @TO_SEARCH IS NULL OR @TO_SEARCH = ''
		EXEC LoaiXe_GetAll
	IF @SEARCH_TYPE = 'LX_ID' 
		SELECT * FROM LoaiXe WHERE LX_ID LIKE '%' + @TO_SEARCH + '%'
	ELSE IF @SEARCH_TYPE = 'LX_TEN'
		SELECT  * FROM LoaiXe WHERE LX_TEN LIKE '%' + @TO_SEARCH + '%'
	ELSE IF @SEARCH_TYPE = 'MO_TA'
				SELECT * FROM LoaiXe WHERE LX_MO_TA LIKE '%' + @TO_SEARCH + '%'
	ELSE
		SELECT * FROM LoaiXe
END
GO